
export const SESSION_TEMPLATES: SessionTemplate[] = [
  {
    id: 'lofi-hip-hop',
    name: 'Lo-Fi Hip Hop',
    description: 'Warm, dusty beats with vinyl texture. Mellow keys over laid-back drums.',
    genre: 'Lo-Fi Hip Hop',
    bpm: 85,
    tags: ['chill', 'lofi', 'hip-hop', 'beats', 'study'],
    tracks: [
      {
        name: 'Drums',
        type: 'midi',
        color: 13,
        instrument: 'drums',
        volume: 0.85,
        pan: 0,
        mute: false,
        solo: false,
      },
      {
        name: 'Bass',
        type: 'midi',
        color: 17,
        instrument: 'bass',
        volume: 0.75,
        pan: 0,
        mute: false,
        solo: false,
      },
      {
        name: 'Keys',
        type: 'midi',
        color: 22,
        instrument: 'keys',
        volume: 0.6,
        pan: -0.15,
        mute: false,
        solo: false,
      },
      {
        name: 'Vinyl Crackle',
        type: 'audio',
        color: 49,
        volume: 0.25,
        pan: 0,
        mute: false,
        solo: false,
      },
    ],
  },
  {
    id: 'jazz-hop',
    name: 'Jazz Hop',
    description: 'Jazz-inflected hip-hop with Rhodes chords and upright bass grooves.',
    genre: 'Jazz Hop',
    bpm: 90,
    tags: ['jazz', 'hip-hop', 'rhodes', 'smooth', 'instrumental'],
    tracks: [
      {
        name: 'Drums',
        type: 'midi',
        color: 14,
        instrument: 'drums',
        volume: 0.8,
        pan: 0,
        mute: false,
        solo: false,
      },
      {
        name: 'Upright Bass',
        type: 'midi',
        color: 30,
        instrument: 'bass',
        volume: 0.7,
        pan: 0.1,
        mute: false,
        solo: false,
      },
      {
        name: 'Rhodes',
        type: 'midi',
        color: 10,
        instrument: 'rhodes',
        volume: 0.55,
        pan: -0.2,
        mute: false,
        solo: false,
      },
      {
        name: 'Sample',
        type: 'audio',
        color: 50,
        volume: 0.5,
        pan: 0.15,
        mute: false,
        solo: false,
      },
    ],
  },
  {
    id: 'ambient-drift',
    name: 'Ambient Drift',
    description: 'Floating pads and field recordings in open space. Meditative and expansive.',
    genre: 'Ambient',
    bpm: 70,
    tags: ['ambient', 'drone', 'meditation', 'atmospheric', 'field-recording'],
    tracks: [
      {
        name: 'Pad A',
        type: 'midi',
        color: 8,
        instrument: 'pad',
        volume: 0.65,
        pan: -0.3,
        mute: false,
        solo: false,
      },
      {
        name: 'Pad B',
        type: 'midi',
        color: 9,
        instrument: 'pad',
        volume: 0.55,
        pan: 0.3,
        mute: false,
        solo: false,
      },
      {
        name: 'Field Recording',
        type: 'audio',
        color: 42,
        volume: 0.35,
        pan: 0,
        mute: false,
        solo: false,
      },
    ],
  },
  {
    id: 'boom-bap',
    name: 'Boom Bap',
    description: 'Hard-hitting drums with chopped samples and raw energy. Classic golden-era feel.',
    genre: 'Boom Bap',
    bpm: 92,
    tags: ['boom-bap', 'hip-hop', 'classic', 'chopped', 'raw'],
    tracks: [
      {
        name: 'Drums',
        type: 'midi',
        color: 58,
        instrument: 'drums',
        volume: 0.9,
        pan: 0,
        mute: false,
        solo: false,
      },
      {
        name: 'Bass',
        type: 'midi',
        color: 17,
        instrument: 'bass',
        volume: 0.8,
        pan: 0,
        mute: false,
        solo: false,
      },
      {
        name: 'Chopped Sample',
        type: 'audio',
        color: 15,
        volume: 0.65,
        pan: -0.1,
        mute: false,
        solo: false,
      },
      {
        name: 'Scratch',
        type: 'audio',
        color: 51,
        volume: 0.45,
        pan: 0.25,
        mute: false,
        solo: false,
      },
    ],
  },
  {
    id: 'rainy-day',
    name: 'Rainy Day',
    description: 'Gentle piano and soft strings over the sound of rain. Nostalgic and tender.',
    genre: 'Cinematic Lo-Fi',
    bpm: 75,
    tags: ['piano', 'strings', 'rain', 'cinematic', 'emotional', 'soft'],
    tracks: [
      {
        name: 'Piano',
        type: 'midi',
        color: 56,
        instrument: 'piano',
        volume: 0.7,
        pan: -0.1,
        mute: false,
        solo: false,
      },
      {
        name: 'Strings',
        type: 'midi',
        color: 10,
        instrument: 'strings',
        volume: 0.5,
        pan: 0.15,
        mute: false,
        solo: false,
      },
      {
        name: 'Rain',
        type: 'audio',
        color: 43,
        volume: 0.3,
        pan: 0,
        mute: false,
        solo: false,
      },
      {
        name: 'Soft Drums',
        type: 'midi',
        color: 52,
        instrument: 'drums',
        volume: 0.55,
        pan: 0,
        mute: false,
        solo: false,
      },
    ],
  },
];

export function getTemplate(id: string): SessionTemplate | undefined {
  return SESSION_TEMPLATES.find((t) => t.id === id);
}

export function getTemplatesByTag(tag: string): SessionTemplate[] {
  return SESSION_TEMPLATES.filter((t) => t.tags.includes(tag));
}

export function templateToConfig(
  template: SessionTemplate,
  outputPath: string
): AbletonSetConfig {
  return {
    name: template.name,
    bpm: template.bpm,
    timeSignature: [4, 4],
    tracks: template.tracks,
    outputPath,
  };
}
